### 1. 求平方根

- 使用二分查找搜索区间 `[low, high]`，同时考虑 `tolerance` 作为终止条件。

- 时间复杂度推导：时间复杂度为 $O(\log_2(N))$。

  - 初始长度 `[low, high]` 可视为 `\max(1, \text{num})`。

  - 迭代次数满足：

    $$
    \frac{\max(1, \text{num})}{2^k} \leq \text{tolerance}
    $$

  - 因此：

    $$
    k \geq \log_2\left(\frac{\max(1, \text{num})}{\text{tolerance}}\right)
    $$

In [1]:
import math
import numpy as np

def my_sqrt(num, tolerance=1e-10):
    # deal with special value
    if num < 0:
        return None
    if num == 0.0 or num == 1.0:
        return num

    # binary search
    low, high = (1, num) if num > 1 else (0, 1)
    while high - low > tolerance:
        mid = low + (high - low)/2.0
        if mid ** 2 > num:
            high = mid
        else:
            low = mid
    
    return low + (high - low)/2.0

def my_sqrt3(num, tolerance=1e-10):
    
    # deal with special value
    if num == 0.0 or num == 1.0:
        return num
    
    flag = 1 if num > 0 else -1
    low, high = (1, abs(num)) if abs(num) > 1 else (0, 1)

    while high - low > tolerance:
        mid = low + (high - low) / 2.0
        if mid ** 3 > abs(num):
            high = mid
        else:
            low = mid
    
    return flag * (low + (high - low)/2.0)

num = -27
print(my_sqrt(num))
print(my_sqrt3(num))


None
-3.00000000001819


### 2. 增量式求均值、方差

- 均值计算
    
    $$
    \mu_n = \mu_{n - 1} + \frac{num - \mu_{n - 1}}{n}
    $$
- 方差计算
    
    $$
    n\sigma_n^2 = (n - 1)\sigma_{n - 1}^2 + (num - \mu_{n - 1})(num - \mu_n)
    $$
  

时间复杂度 $O(N)$

In [2]:
# 增量式计算均值、方差
def my_mean_var(nums):

    cnt = 0
    mean = 0.0
    M2 = 0.0

    for num in nums:

        cnt += 1
        delta1 = num - mean
        mean += (num - mean) / cnt
        delta2 = num - mean
        M2 += delta1 * delta2

    return mean, M2/cnt 

nums = np.random.rand(10)
print(my_mean_var(nums))
print(np.mean(nums))
print(np.var(nums))       


(0.4954332396440718, 0.11795675523733662)
0.49543323964407177
0.11795675523733659


### 3. 矩阵乘法

- 时间复杂度：$O(mnp)$

- 矩阵连乘

In [3]:
# 矩阵乘法
def my_dot(A, B):

    m, n = A.shape
    n_b, p = B.shape

    if n != n_b:
        return None

    ans = np.zeros([m, p])
    for i in range(m):
        for j in range(p):
            for k in range(n):
                ans[i][j] += A[i][k] * B[k][j]

    return ans

A = np.random.rand(2, 3)
B = np.random.rand(3, 2)
print(A)
print(my_dot(A, B))
print(np.dot(A, B))

[[0.01579536 0.0453052  0.02046671]
 [0.9076387  0.06004818 0.13885978]]
[[0.0302674  0.05054585]
 [0.29371248 0.57986842]]
[[0.0302674  0.05054585]
 [0.29371248 0.57986842]]
